version: "2"
services:
  web:
    build: .
    image: contacts
    container_name: contacts
    ports:
      - "4030:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/mongo-test
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"