version: "2"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/mongo-test
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"